### ISSUE TITLE
Managing cluster after diverging from kops 

### ISSUE THREAD

**Issue by MirrorZ** [aws-samples/aws-workshop-for-kubernetes#151]
Using terraform output from kops enables one to provision the kubernetes cluster. Terraform can then be used to add specific IAM roles, security groups etc and the state diverges from what was the intially set up by kops. So how can kops be used to carry out more granular updates with terraform such as enabling batch jobs for the current kubernetes cluster.

**Comment by arun-gupta** [comment]
Terraform workflow is documented at https://github.com/kubernetes/kops/blob/master/docs/terraform.md

The exact use case will be covered as part of https://github.com/arun-gupta/kubernetes-aws-workshop/issues/135

Here is discussion from #kops slack channel:

```
shadoi [10:46 PM] Obviously terraform can't know anything about that very well (which is one of the main reasons not to use terraform to manage clusters exclusively IMO). (edited)
[10:47] `kops update cluster` will apply changes to the cluster spec and a `kops rolling-update cluster` will apply them safely to masters and nodes, that's pretty much always going to be the case. (edited)
[10:48] It might be interesting to see what's possible with the new kops api server though.
chrislovecnm [10:55 PM] @arungupta we should have a tf workflow documented
[10:56] I know we have notes in update for how to proceed
```

**Comment by chrislovecnm** [comment]
@MirrorZ can you move this issue over to the kops repo?  Great questions and I would love to continue the conversation there.

**Comment by MirrorZ** [comment]
@chrislovecnm Here you go https://github.com/kubernetes/kops/issues/3961.

**Comment by arun-gupta** [comment]
Closing this issue
