### ISSUE TITLE
Nginx ingress controller in combination with kube-lego

### ISSUE THREAD

**Issue by bpasson** [aws-samples/aws-workshop-for-kubernetes#171]
It would be really nice to have the nginx ingress part of the workshop also contain kube-lego for requesting on the fly SSL certificates from Lets Encrypt. More information can be found [here](https://blog.jetstack.io/blog/kube-lego/).

**Comment by arun-gupta** [comment]
This is related to https://github.com/arun-gupta/kubernetes-aws-workshop/issues/30
