### ISSUE TITLE
minikube v1.7.5 and not v1.8.0

### ISSUE THREAD

**Issue by MitchyBAwesome** [aws-samples/aws-workshop-for-kubernetes#188]
The documentation shows that you should be running v1.8.0, however, when following the instructions v1.7.5 is installed. This may be confusing to some people. It might be worth updating the documentation, or adding a note about the fact that v1.7.5 is okay.

**Comment by arun-gupta** [comment]
Can you show what does `minikube version` shows?

I see:

```
$ minikube version
minikube version: v0.23.0
```

**Comment by scottmalkie** [comment]
I believe this can be closed thanks to #286, which due to 24.1 upgrade should install 1.8.0.
