### ISSUE TITLE
Running minikube for Windows

### ISSUE THREAD

**Issue by dalbhanj** [aws-samples/aws-workshop-for-kubernetes#201]
Specify other methods to install minikube for developer environment for Windows by using an EC2 instance. 
Add it to https://github.com/arun-gupta/kubernetes-aws-workshop/tree/master/getting-started#setup-on-windows

**Comment by dalbhanj** [comment]
assign to @enghwa

**Comment by arun-gupta** [comment]
@riywo feel free to send a PR referring this issue

**Comment by enghwa** [comment]
@dalbhanj @arun-gupta  added instruction for ec2/ubuntu for minikube https://github.com/arun-gupta/kubernetes-aws-workshop/pull/237

**Comment by dalbhanj** [comment]
Closing this issue as this is already PR'ed https://github.com/aws-samples/aws-workshop-for-kubernetes/pull/237
