### ISSUE TITLE
Update Calico Install notes

### ISSUE THREAD

**Issue by chrislovecnm** [aws-samples/aws-workshop-for-kubernetes#236]
As of kops 1.8.x https://github.com/arun-gupta/kubernetes-aws-workshop/tree/master/calico#update-calico-to-241-in-kops-17x will be dated.  We may have a couple of updates, but kops 1.8.x will have the latest Calico.

**Comment by wombat** [comment]
@chrislovecnm yes we know - calico in kops 1.7.x is so old, that network-polices wouldn´t have worked

**Comment by chrislovecnm** [comment]
Submitting a PR for kops 1.8, which includes latest Calico

**Comment by christopherhein** [comment]
@chrislovecnm that PR was merged, correct? Assuming we can close this?

**Comment by chrislovecnm** [comment]
Correct it was merged
