### ISSUE TITLE
changing CNI on a K8s is not supported

### ISSUE THREAD

**Issue by chrislovecnm** [aws-samples/aws-workshop-for-kubernetes#242]
We have instructions here https://github.com/arun-gupta/kubernetes-aws-workshop/tree/master/calico#installation

These instructions cannot be used on a live cluster.

This will cause downtime in production and requires many manual steps to pull off.  We do not have this fully documented or supported in kops.

Changing CNI providers is not recommended.

**Comment by buzzsurfr** [comment]
Ultimately fixed in #269
