### ISSUE TITLE
Move VirtualBox installation to pre-reqs

### ISSUE THREAD

**Issue by arun-gupta** [aws-samples/aws-workshop-for-kubernetes#257]
VirtualBox installation is required for minikube to work. Instead of scattering the instructions over different operating system, move it to the pre-reqs chapter.

**Comment by christopherhein** [comment]
Are we keeping Minikube in here now that we have Docker + K8s support on Mac & Windows?

**Comment by arun-gupta** [comment]
This would be redundant after https://github.com/aws-samples/aws-workshop-for-kubernetes/issues/315

**Comment by buzzsurfr** [comment]
Since moving to kops and then EKS, this is no longer necessary.
