### ISSUE TITLE
Kube dashboard broken for Kubernetes Cluster Monitoring

### ISSUE THREAD

**Issue by jasonmacdonald** [aws-samples/aws-workshop-for-kubernetes#260]
Seems a change was made to https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml regarding RBAC that has broken the first step in https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/cluster-monitoring

**Comment by MCLDG** [comment]
PR#275 should fix this. A quick fix that resolves the issue. Dashboard has been upgraded to support v1.8 of K8s, which includes the RBAC API as GA, not the previous Beta version. The GA version is not supported in K8s v1.7

**Comment by MCLDG** [comment]
@arun-gupta too fast for me :-)
