### ISSUE TITLE
KOPS couldn't read from the s3 bucket

### ISSUE THREAD

**Issue by jturegano** [aws-samples/aws-workshop-for-kubernetes#261]
I've run into this issue while creating the cluster:

kops create cluster \
>   --name example.cluster.k8s.local \
>   --zones $AWS_AVAILABILITY_ZONES \
>   --yes

error reading cluster configuration "example.cluster.k8s.local": error reading s3://example-state-store-<eidted>/example.cluster.k8s.local/config: Unable to list AWS regions: NoCredentialProviders: no valid providers in chain. Deprecated. 
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors

The bucket was in the right region and I was able to read and write to the bucket correctly from the AWS CLI.

Apparently the way I configured the user through the usage of profiles had some kind of problem with the AWS GO SDK and required to setup an additional environment variable for it to work:

export AWS_SDK_LOAD_CONFIG=1

This solved the issue and the deployment of the cluster commenced.

**Comment by chrislovecnm** [comment]
There are differences between the python SDK and the go SDK.  `kops` 1.8 also includes updated aws go API, so more information would be helpful.  This is something that we need to document a bit better in kops.

**Comment by christopherhein** [comment]
#308 closes this issue.
