### ISSUE TITLE
Cleaning after the workshop

### ISSUE THREAD

**Issue by jturegano** [aws-samples/aws-workshop-for-kubernetes#262]
It would be great to have a list of commands to clean your AWS account after the workshop, couldn't find one in the repo. Specially IAM roles, S3 buckets, etc... as there is a way to delete your cluster.

**Comment by chrislovecnm** [comment]
`kops get cluster`
`kops delete cluster --name $CLUSTER_NAME`
`kops delete cluster --name $CLUSTER_NAME --yes`
Then delete your bucket.  I think we have them, but I another page would be good

**Comment by jturegano** [comment]
Hi Chris, yeah steps to delete the cluster are included but not to leave the account in the initial state it was, check my original comment about IAM roles, buckets, etc... Some other similar exercises relay on a cloud formation template that creates a stack containing all the required steps, once finished you can delete the stack and leave everything as it was before. This will not include the setup of the cluster but the steps to get the account ready. If this is not feasible just instructions could be handy. Cheers.

**Comment by dalbhanj** [comment]
Hi @jturegano,
Doesn't this cover the topic? https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/cluster-install#delete-cluster

All the workshop tutorials are self-contained or at least that's the goal. Can you point to specific tutorials where cleanup is not mentioned so that we can address those?

**Comment by jturegano** [comment]
The initial pre-requisites readme instructs you to create the following IAM resources:

```
$ aws iam create-group --group-name k8s-workshop

$ aws iam attach-group-policy --policy-arn arn:aws:iam::aws:policy/AmazonEC2FullAccess --group-name k8s-workshop
$ aws iam attach-group-policy --policy-arn arn:aws:iam::aws:policy/AmazonRoute53FullAccess --group-name k8s-workshop
$ aws iam attach-group-policy --policy-arn arn:aws:iam::aws:policy/AmazonS3FullAccess --group-name k8s-workshop
$ aws iam attach-group-policy --policy-arn arn:aws:iam::aws:policy/IAMFullAccess --group-name k8s-workshop
$ aws iam attach-group-policy --policy-arn arn:aws:iam::aws:policy/AmazonVPCFullAccess --group-name k8s-workshop

$ aws iam create-user --user-name k8s-workshop

$ aws iam add-user-to-group --user-name k8s-workshop --group-name k8s-workshop

$ aws iam create-access-key --user-name k8s-workshop
```

I haven't found instructions on how to clean those up in the repo, which must be trivial by mostly running deletes for those creations or using the console but a good advice for newbies so they don't leave IAM unused resources in their accounts after the workshop.

Let me know if this still doesn't make sense.

**Comment by christopherhein** [comment]
Hey @jturegano seems like a reasonable thing to add, would you like to take a stab at putting in a PR?

Probably could be as easy as:
```
$ aws iam delete-group --group-name k8s-workshop
$ aws iam delete-user --user-name k8s-workshop
```

Maybe append to the end of [cluster-install#delete-cluster](https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/cluster-install#delete-a-cluster)

**Comment by buzzsurfr** [comment]
Changes were made in February that simplified the cleanup process by placing everything into a series of CloudFormation templates, and we now include instructions on cleaning up after the workshop at https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/01-path-basics/101-start-here#workshop-cleanup.
