### ISSUE TITLE
repo house cleaning

### ISSUE THREAD

**Issue by chrislovecnm** [aws-samples/aws-workshop-for-kubernetes#279]
We may want to think about

1. contributor guide
2. code of conduct
3. label for new contributor

Does AWS have standards for this @arun-gupta

**Comment by arun-gupta** [comment]
Checking and will get back

**Comment by hyandell** [comment]
We'll be uploading a contributing guide w/ code of conduct to the repo later this year; I wanted to wait until re:invent was past before pushing files to a lot of repos <coward-or-sane/> :)

We don't have a standard new-user issue label. Is there a common label you're aware of?

**Comment by chrislovecnm** [comment]
@hyandell `good-starter-issue` label is quite common, also `help-wanted` label.  Documenting the label in the contributor guide, and using it consistently in the project is what I recommend.  We just `good-starter-issue` in kops.

**Comment by hyandell** [comment]
'help wanted' is a GitHub default (generally I'm expecting that we're using the GH defaults). I don't see any of our projects using 'good starter issue'.

I'll add a piece on labels, and specifically 'help wanted', to the planned standard CONTRIBUTOR guide.

**Comment by buzzsurfr** [comment]
1. Contributor guide is now proposed in #496 
1. We will use the AWS Open Source Code of Conduct.  PR #483 
1. Created the [`good-starter-issue`](https://github.com/aws-samples/aws-workshop-for-kubernetes/labels/good%20starter%20issue) label.
