### ISSUE TITLE
etcd

### ISSUE THREAD

**Issue by chrislovecnm** [aws-samples/aws-workshop-for-kubernetes#281]
https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/best-practices

> In most cases it is advisable to use an etcd cluster consisting of five nodes. This setup ensures that up to two nodes can get unhealthy without loosing data. Bigger clusters have also a bigger failure tolerance, but suffer in decreasing write performance as the data has to be synchronized to more machines.

So how does AWS recommend to set this up with 3 AZ?  I think we need nine etcd nodes for full amazing HA :(  @arun-gupta can we track down the CoreOS folks at kubecon,  maybe some of your gurus and resolve this?

I need to understand how this works with the internals of etcd.  Now if AWS offers hosted etcd, this becomes a mute point.

Unless you need 5 9's on the control plane you do not need HA masters.  We should talk about how to lay this out.

**Comment by buzzsurfr** [comment]
The reference page no longer exists, and we have moved to using EKS or kops which builds the etcd cluster for the user.
