### ISSUE TITLE
Inconsistent handling of dynamic values

### ISSUE THREAD

**Issue by RisingPhorce** [aws-samples/aws-workshop-for-kubernetes#291]
On Page https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/getting-started#execute-a-shell-on-the-running-pod

Some commands use <dyamic-variable> nomenclature other use a copy/paste of someone else's variables with the description block noting to change certain values.

**Comment by buzzsurfr** [comment]
The workshop has been reworked and this section was updated when the learning paths were added in #334
