### ISSUE TITLE
Wrong name - command doesn't work

### ISSUE THREAD

**Issue by RisingPhorce** [aws-samples/aws-workshop-for-kubernetes#296]
On Page https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/developer-concepts#create-a-pod

Custom Namespace Step 8 should be nginx-deployment-ns instead of nginx-deployment

kubectl get deployments/nginx-deployment-ns -n dev -o jsonpath={.metadata.namespace}
dev

**Comment by scottmalkie** [comment]
Fixed in #295.
