### ISSUE TITLE
/dev/random issue

### ISSUE THREAD

**Issue by jtfogarty** [aws-samples/aws-workshop-for-kubernetes#312]
Shouldn't the random in the below be urandom?  

export S3_BUCKET=example-state-store-$(cat /dev/random | LC_ALL=C tr -dc "[:alpha:]" | tr '[:upper:]' '[:lower:]' | head -c 32)

**Comment by arun-gupta** [comment]
@cloudymind

**Comment by arun-gupta** [comment]
Are you seeing an unexpected behavior with `random`?

**Comment by jtfogarty** [comment]
it does not return.  I tried on ubuntu and on redhat.

**Comment by arun-gupta** [comment]
Verified that `urandom` works on OSX. Can you confirm `urandom` works on Ubuntu and Windows (with Linux shell)?

**Comment by jtfogarty** [comment]
urandom works on Ubuntu and Redhat.

**Comment by arun-gupta** [comment]
@jtfogarty send a PR?
