### ISSUE TITLE
Custom AMI Issue, Tags && EC2 IAM Role 

### ISSUE THREAD

**Issue by dshamanthreddy** [aws-samples/aws-workshop-for-kubernetes#313]
While creating Gossip Based Kubernetes Cluster with kops , I use this command 

$ kops create cluster \
  --name example.cluster.k8s.local \
  --zones $AWS_AVAILABILITY_ZONES \
  --yes

The above command run perfect but I need the master and node to be on my Custom AMI  and also have My Custom Tags to master and nodes.( This has to be done at cluster creation only or else my lambda will knock the instance down)

Can you please let me know how to pass Ec2 Instance Iam role which is already created.

**Comment by arun-gupta** [comment]
@dshamanthreddy kops allows a custom AMI to be specified using `--image` and tags to be specified using `--cloud-labels`. Have you tried them?

Is the IAM role to be assigned to each node in the cluster?

**Comment by dshamanthreddy** [comment]
@arun-gupta  Thanks for getting back,Can I try some thing like this 
$ kops create cluster 
--name example.cluster.k8s.local 
--zones $AWS_AVAILABILITY_ZONES 
--yes
--image  ami868561
--Cloud-labels  name:dev, role:xyz


So if I want the master and nodes running with xyz Ec2iamrole ,how can I pass then above ?

**Comment by arun-gupta** [comment]
@dshamanthreddy Read more at https://github.com/kubernetes/kops/blob/master/docs/iam_roles.md

Closing this issue if there are issues with the content here.
