### ISSUE TITLE
Simplify on-boarding experience

### ISSUE THREAD

**Issue by arun-gupta** [aws-samples/aws-workshop-for-kubernetes#315]
Use Cloud 9 to investigate how the on-boarding experience can be simplified.

**Comment by dalbhanj** [comment]
WIP here: https://github.com/aws-samples/aws-workshop-for-kubernetes/wiki/Cloud9

**Comment by christopherhein** [comment]
would you all agree this should be closed?

**Comment by dalbhanj** [comment]
yes, automated cloud9 dev environment (https://github.com/aws-samples/aws-workshop-for-kubernetes/pull/326) and the new learning paths solves this issue (https://github.com/aws-samples/aws-workshop-for-kubernetes/pull/334)
