### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by chrislovecnm** [aws-samples/aws-workshop-for-kubernetes#340]
https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/01-path-basics/101-start-here

contains

https://github.com/aws-samples/aws-workshop-for-kubernetes/blob/master/01-path-basics/101-start-here/aws-permissions.adoc

Which is busted

**Comment by buzzsurfr** [comment]
Could not find aws-permissions.adoc from the git log.

Need to determine what permissions are necessary to launch the workshop and include those.  A temporary fix to the workshop may be to request Administrator permissions.

**Comment by geremyCohen** [comment]
Dupe of https://github.com/aws-samples/aws-workshop-for-kubernetes/issues/453

**Comment by geremyCohen** [comment]
https://github.com/aws-samples/aws-workshop-for-kubernetes/pull/516
