### ISSUE TITLE
Use Cloud9 preview functionality for nginx pod port forwarding in 01-path-basics/103-kubernetes-concepts

### ISSUE THREAD

**Issue by jpignata** [aws-samples/aws-workshop-for-kubernetes#343]
Since we're now running under Cloud9, we can take advantage of its [preview functionality][preview] by binding to port 8080 which would allow the participant to see their container just by hitting the preview button. It's a small change:

```console
kubectl -n default port-forward $(kubectl -n default get pod -l name=nginx-pod -o jsonpath='{.items[0].metadata.name}') 8080:80
```

And then instead of `open` or `curl`, instruct the participant to click **Preview**.

[preview]: https://docs.aws.amazon.com/cloud9/latest/user-guide/app-preview.html

**Comment by scottmalkie** [comment]
Fixed with #348
