### ISSUE TITLE
$AWS_AVAILABILITY_ZONES Not Set During Manual Env Config

### ISSUE THREAD

**Issue by samhays** [aws-samples/aws-workshop-for-kubernetes#344]
The manual steps calls out the export for s3 buckets but there is no call out on how to configure export $AWS_AVAILABILITY_ZONES

kops create cluster --name example.cluster.k8s.local --zones $AWS_AVAILABILITY_ZONES --yes will return a not found

**Comment by buzzsurfr** [comment]
Added the steps from the build script.
