### ISSUE TITLE
Deploy to New VPC in Singapore fails

### ISSUE THREAD

**Issue by velniukas** [aws-samples/aws-workshop-for-kubernetes#345]
Fails at these 2 points:

1. awscodestar-mylittlepony-lambda

20:49:20 UTC-0700 | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack | awscodestar-mylittlepony-lambda | No export named mylittlepony-ap-southeast-1-LambdaTrustRole found. Rollback requested by user.
-- | -- | -- | -- | --
  | Physical ID:arn:aws:cloudformation:ap-southeast-1:417089339528:stack/awscodestar-mylittlepony-lambda/95dbfbb0-77fe-11e7-9fa3-500c336f3856

2. Linux Bastion

22:30:20 UTC-0800 | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack | Linux-bastion | Template error: Subnet doesn't exist. Rollback requested by user.
-- | -- | -- | -- | --
  | Physical ID:arn:aws:cloudformation:ap-southeast-1:417089339528:stack/Linux-bastion/b75ff3d0-fa86-11e7-abe0-500c336f5a8e

**Comment by dalbhanj** [comment]
Hi @velniukas,

Assuming you are referring to https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/01-path-basics/101-start-here#aws-cloud9-console?

I was unable to replicate this issue on my end. CloudFormation launched successfully with new VPC option in Singapore region 

Can you post the Errors you see in Events tab of CloudFormation?
