### ISSUE TITLE
Add a source at the end of lab-ide-build.sh

### ISSUE THREAD

**Issue by samhays** [aws-samples/aws-workshop-for-kubernetes#350]
Currently at the end of lab-ide-build.sh the following env variables are echo'd into .bash_profile but there isn't a source command following the set to refresh the shell

"# Persist lab variables
echo "AWS_AVAILABILITY_ZONES=$AWS_AVAILABILITY_ZONES" >> ~/.bash_profile
echo "KOPS_STATE_STORE=$KOPS_STATE_STORE" >> ~/.bash_profile
echo "export AWS_AVAILABILITY_ZONES KOPS_STATE_STORE" >> ~/.bash_profile"

Add something like "source ~/.bash_profile"

**Comment by buzzsurfr** [comment]
Running the script will also add those variables to the current bash session, see [lab-ide-build.sh](https://github.com/aws-samples/aws-workshop-for-kubernetes/blob/master/01-path-basics/101-start-here/scripts/lab-ide-build.sh) lines 28:37.

Note that [Build Script](https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/01-path-basics/101-start-here#build-script) instructions in the 101 lab require an extra period to call the build script:

    . ./lab-ide-build.sh

The additional period runs the script in the current shell (and not in a subshell).  It is synonymous with `source`. (Ref: [https://ss64.com/bash/source.html](https://ss64.com/bash/source.html))

**Comment by dalbhanj** [comment]
Resolving...
