### ISSUE TITLE
Error on kubectl rollout history command output

### ISSUE THREAD

**Issue by crancurello** [aws-samples/aws-workshop-for-kubernetes#353]
When reviewing the rollout history for my deployment, it only shows two revisions:

At first it was only showing the first and last revision but when recreating everything it showed the last two revisions: i.e.

jesushum:~/environment/aws-workshop-for-kubernetes/01-path-basics/103-kubernetes-concepts/templates (master) $ kubectl rollout history deployment/nginx-deployment                                  
deployments "nginx-deployment"
REVISION  CHANGE-CAUSE
5         kubectl scale deployment/nginx-deployment --replicas=5 --record=true
6         kubectl scale deployment/nginx-deployment --replicas=10 --record=true

So I cannot go to revision 1, but only switch between current and last revision

**Comment by christopherhein** [comment]
This is actually the expected output of `rollout history` when you roll back to a previous revision, the Deployment reuses the template and changes the number so that it is the latest revision. IE what was 4 is now 6 and if you undo 6 to 5 it will change it to 7 and you will see an output like:

```
REVISION CHANGE-CAUSE
6 kubectl scale deployment/nginx-deployment --replicas=5 --record=true
7 kubectl scale deployment/nginx-deployment --replicas=10 --record=true
```
