### ISSUE TITLE
pod.yaml line 9 needs indentation 

### ISSUE THREAD

**Issue by samhays** [aws-samples/aws-workshop-for-kubernetes#357]
From Create a pod on https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/01-path-basics/103-kubernetes-concepts

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx-pod
spec:
  containers:
- name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80

As written as currently formatted it returns:

kubectl apply -f pod.yaml
error: error converting YAML to JSON: yaml: line 8: did not find expected key

Written as:

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80

kubectl apply -f pod.yaml                                                                                                     
pod "nginx-pod" created

**Comment by christopherhein** [comment]
PR would be greatly appreciated. @samhays

**Comment by buzzsurfr** [comment]
Fixed in #370
