### ISSUE TITLE
forwarding and open http://localhost:8088/ step - pls check 

### ISSUE THREAD

**Issue by rjnavigator** [aws-samples/aws-workshop-for-kubernetes#359]
$ kubectl -n default port-forward $(kubectl -n default get pod -l name=nginx-pod -o jsonpath='{.items[0].metadata.name}') 8088:80

the port forwarding works

but after that, 
$ open http://localhost:8088/
where should this be executed ? 
On separate terminal ? 

the forwarding takes time and it doesnt complete.

**Comment by scottmalkie** [comment]
Fixed with #348
