### ISSUE TITLE
Dashboard command does not return and work

### ISSUE THREAD

**Issue by nvashish123** [aws-samples/aws-workshop-for-kubernetes#364]
in the 201-cluster-monitoring part -

when the command is run to create the Dashboard, the dashboard url is not accessible by either the full URL - http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/

or by just accessing the localhost - 127.0.0.1:8001

I am not on amazon VPN while trying this.

**Comment by christopherhein** [comment]
To confirm this was while using `kubectl proxy` ?

**Comment by nvashish123** [comment]
correct, using kubectl proxy

**Comment by riywo** [comment]
Since the proxy is running on the Cloud9 instance, you can hit the localhost:8001 from Cloud9 shell by curl. But accessing from your local browser is not available to localhost:8001.

Cloud9 has a functionality called "preview", which is a Cloud9 provided proxy to port 8080 on Cloud9 instance, so I'd tried to access https://aaaaaaaaaaaaaaaaaa.vfs.cloud9.us-east-1.amazonaws.com/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/ , but it returns 403.

**Comment by diegodalmolin** [comment]
Solved this by:
1 - installing kubectl locally at my workstation
2 - exporting cloud9 .kube/config file (kubectl config view --flatten=true)
3 - Imported that to my workstation .kube/config
4 - run kubeclt proxy locally.

thanks Omar

**Comment by arun-gupta** [comment]
@nathanpeck experienced this in a recent workshop as well. Similar to https://github.com/aws-samples/aws-workshop-for-kubernetes/issues/377

**Comment by christopherhein** [comment]
We probably should put this on hold until - https://github.com/kubernetes/kubernetes/pull/46517 since then in Cloud9 we could have it bind to `0.0.0.0` and the preview "should" (famous last words) should work. :+1:

**Comment by subhrang** [comment]
Thanks diegodalmolin.
Your method worked

**Comment by minghsieh-prenetics** [comment]
Per issue comment [here](https://github.com/kubernetes/dashboard/issues/692#issuecomment-327416830) and [here](https://github.com/kubernetes/dashboard/issues/692#issuecomment-336433055) suggested following two works on Cloud9 ide preview:

```
kubectl proxy --address 0.0.0.0 --accept-hosts '.*' --port 8080
kubectl proxy --address 0.0.0.0 --disable-filter=true --port 8080
```
Just for the record, in case you "really" need to run `kubectl proxy` on Cloud9 ide preview.

**Comment by christopherhein** [comment]
thanks @minghsieh-prenetics ! Did you test this? If so would you be interested in putting in a Pull Request with the documentation changes?

**Comment by minghsieh-prenetics** [comment]
@christopherhein Yes I did. We, however, will need to route other ports (e.g. 401-configmaps redis port, 40x, etc.), depends on context / workshop section materials.

**Comment by minghsieh-prenetics** [comment]
@christopherhein 👆  PR.

**Comment by riywo** [comment]
It worked for me! Excellent!
