### ISSUE TITLE
multi-master cluster link is broken

### ISSUE THREAD

**Issue by nvashish123** [aws-samples/aws-workshop-for-kubernetes#365]
in the 202-service-mesh section -

the link for the multi-master multi node cluster under the 'Create Kubernetes cluster' is broken. The same link is also broken on the previous section under the 'prerequisites' section -

```
Create Kubernetes cluster
This chapter uses a cluster with 3 master nodes and 5 worker nodes as described here: multi-master, multi-node gossip based cluster.

```

**Comment by bodom0015** [comment]
I believe that this information has moved here: https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/01-path-basics/102-your-first-cluster#multi-master-cluster

**Comment by geremyCohen** [comment]
Will use the same text as this PR after its finalized: #499
