### ISSUE TITLE
Deploying applications using Kubernetes Helm chart link is broken

### ISSUE THREAD

**Issue by diegodalmolin** [aws-samples/aws-workshop-for-kubernetes#371]
Install a Java application as explained in Deploying applications using Kubernetes Helm charts is broken
link moved here: https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/03-path-application-development/306-app-management-with-helm

**Comment by geremyCohen** [comment]
@diegodalmolin can your provide the url of the page this broken link appears on ?

**Comment by geremyCohen** [comment]
I am unable to find any broken links on this page aside from the cluster-prereq text which has been added to https://github.com/aws-samples/aws-workshop-for-kubernetes/issues/512 so I will close this ticket out
