### ISSUE TITLE
Add s3://aws-kubernetes-artifacts/lab-ide-build.sh to the repo

### ISSUE THREAD

**Issue by arun-gupta** [aws-samples/aws-workshop-for-kubernetes#379]
s3://aws-kubernetes-artifacts/lab-ide-build.sh is used to setup environment for the workshop. This file is only at S3 and not checked into the repo, and needs to be.

**Comment by dalbhanj** [comment]
@arun-gupta, the script is located here: https://github.com/aws-samples/aws-workshop-for-kubernetes/blob/master/01-path-basics/101-start-here/scripts/lab-ide-build.sh

Are you seeing diffs between the both files?
