### ISSUE TITLE
for anyone getting `InvalidClientTokenId: The security token included in the request is invalid` error

### ISSUE THREAD

**Issue by foray1010** [aws-samples/aws-workshop-for-kubernetes#391]
just go to cloud9 => click `AWS cloud9` on top left hand corner => `Preference` => `AWS settings` => disable `AWS managed temporary credentials`
and try tutorial again, hope it helps

**Comment by jyjohnson** [comment]
this is fixed my issue when using Cloud 9 via Systems Manager (ssm) access.
