### ISSUE TITLE
Create a module to show Kubernetes chaos engineering with the Chaos Toolkit

### ISSUE THREAD

**Issue by russmiles** [aws-samples/aws-workshop-for-kubernetes#394]
The open source chaos toolkit includes the capability to run chaos against Kubernetes. This ticket encompasses adding a new module to show a minimal chaos experiment and how to interpret the experimental outcomes.

**Comment by arun-gupta** [comment]
Looking forward to the PR

**Comment by russmiles** [comment]
Excellent! Can you assign this issue to me @arun-gupta please?

**Comment by arun-gupta** [comment]
You need to be part of the org to be assigned an issue. Just send the PR referring this issue.

**Comment by russmiles** [comment]
Will do, thanks!

**Comment by russmiles** [comment]
Do you have an idea within the courseware's workflow where this module would sit best @arun-gupta ? I was thinking making this the 309-chaos-engineering module?

**Comment by arun-gupta** [comment]
I think that's a logical place for this to fit in

**Comment by christopherhein** [comment]
depending on when you submit `309` might be taken; I'm submitting a PR for https://github.com/aws-samples/aws-workshop-for-kubernetes/issues/70 today using the `309` module

**Comment by russmiles** [comment]
@arun-gupta first draft of chaos engineering chapter is now ready to review in this PR: https://github.com/aws-samples/aws-workshop-for-kubernetes/pull/397

**Comment by russmiles** [comment]
One thing we didn't include was a definitive answer to the weakness that the chaos engineering experiment detected, as this is actually beyond the remit of chaos engineering. There are lots of options that could be used of course, including circuit breakers from app code or service meshes. Just wanted to highlight that we kept this chapter simple and tight by focussing the practical work on the specific job of chaos engineering, i.e. to discover weaknesses.
