### ISSUE TITLE
IAM link broken

### ISSUE THREAD

**Issue by RisingPhorce** [aws-samples/aws-workshop-for-kubernetes#398]
https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/01-path-basics/101-start-here

Section:  Configure the AWS CLI

Link:  these permissions returns 404 Not Found

**Comment by geremyCohen** [comment]
@RisingPhorce ty for filing the issue, this issue was duped at https://github.com/aws-samples/aws-workshop-for-kubernetes/issues/453 so I'll look into fixing it there.
