### ISSUE TITLE
K8S Bug 55278 marked stale

### ISSUE THREAD

**Issue by RisingPhorce** [aws-samples/aws-workshop-for-kubernetes#403]
The QoS bug referenced in https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/01-path-basics/103-kubernetes-concepts#quality-of-service was recently marked stale by the k8s-ci-bot.  

https://github.com/kubernetes/kubernetes/issues/55278

**Comment by christopherhein** [comment]
Apparently this is a feature of kops, not a bug. Closing this issue.
