### ISSUE TITLE
Link to "02-path-working-with-clusters/helm" is not working

### ISSUE THREAD

**Issue by apjneeraj** [aws-samples/aws-workshop-for-kubernetes#417]
url : https://github.com/aws-samples/aws-workshop-for-kubernetes/blob/master/02-path-working-with-clusters/helm seems to be broken.

**Comment by christopherhein** [comment]
Hey @apjneeraj where is this link being referenced from? Thanks!

**Comment by apjneeraj** [comment]
@christopherhein : it is at this page: 
https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/02-path-working-with-clusters/201-cluster-monitoring#kubernetes-dashboard

The text on page is : "Install a Java application as explained in Deploying applications using Kubernetes Helm charts."

**Comment by christopherhein** [comment]
Thanks! Any chance you’d be interested in putting in a PR with the fix? :$

**Comment by geremyCohen** [comment]
This is now working.
