### ISSUE TITLE
Broken link in 02-path-working-with-clusters/201-cluster-monitoring

### ISSUE THREAD

**Issue by thiagoalves** [aws-samples/aws-workshop-for-kubernetes#434]
https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/02-path-working-with-clusters/201-cluster-monitoring

In the "prerequisites" section there's a broken link in the paragraph below:

This chapter uses a cluster with 3 master nodes and 5 worker nodes as described here: multi-master, multi-node gossip based cluster.

**Comment by geremyCohen** [comment]
PR submitted
