### ISSUE TITLE
kubernetes dashboard rbac error

### ISSUE THREAD

**Issue by siggy** [aws-samples/aws-workshop-for-kubernetes#435]
following along here:
https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/02-path-working-with-clusters/201-cluster-monitoring#kubernetes-dashboard
... i get errors on the dashboard that it does not have permission at the cluster scope. perhaps different rbac roles are needed?

**Comment by weitzj** [comment]
Happens to me as well, public multimaster, multinode cluster in `us-east-1`

**Comment by svenfinke** [comment]
Just try to use the namespace-controller token instead of the default one, that works fine :)

**Comment by nathanpeck** [comment]
I just opened PR #448 to address this issue. Thanks for your help!
