### ISSUE TITLE
01-path-basics/103-kubernetes-concepts slight doc correction

### ISSUE THREAD

**Issue by amollenkopf** [aws-samples/aws-workshop-for-kubernetes#436]
In 01-path-basics/103-kubernetes-concepts section that leads with
"Alternatively, a namespace can be created using kubectl as well."
The command in 2. Create a Deployment reads:
<code>kubectl -n dev2 apply -f templates/deployment.yaml</code>
but should not have the 'templates' folder and should read:
<code> kubectl -n dev2 apply -f deployment.yaml</code>

**Comment by buzzsurfr** [comment]
Close. Fixed in #437.
