### ISSUE TITLE
Update command formatting

### ISSUE THREAD

**Issue by cplewis** [aws-samples/aws-workshop-for-kubernetes#451]
Track: OpenShift on AWS
Text: --network=container:<alias> to link to the wordpress container bash $ ls -lZd ~/workspace/pv/mysql $ docker run -d --network=container:wordpress -v ~/workspace/pv/mysql:/var/lib/mysql:z -e DBUSER=user -e DBPASS=mypassword -e DBNAME=mydb --name mariadb mariadb

Issue Base URL: http://openshift.awsworkshop.io/index.html

**Comment by christopherhein** [comment]
Not the right repo. @mandusm looks like we need to define the `repo_url: https://github.com/aws-samples/aws-workshop-for-kubernetes` to your repo's `workshop.yaml` 👍
