### ISSUE TITLE
Separate commands

### ISSUE THREAD

**Issue by cplewis** [aws-samples/aws-workshop-for-kubernetes#452]
Track: OpenShift on AWS
Text: $ docker tag mariadb localhost:5000/mariadb $ docker tag wordpress localhost:5000/wordpress $ docker images
Issue Base URL: http://openshift.awsworkshop.io/index.html

**Comment by christopherhein** [comment]
Not the right repo. @mandusm looks like we need to define the `repo_url: https://github.com/aws-samples/aws-workshop-for-kubernetes` to your repo's `workshop.yaml` 👍
