### ISSUE TITLE
Broken link in Configure the AWS CLI Section of Kubernetes - Setup Cloud9 Development Environment page

### ISSUE THREAD

**Issue by C24IO** [aws-samples/aws-workshop-for-kubernetes#453]
In this section - 

https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/01-path-basics/101-start-here#configure-the-aws-cli

This line - Make sure you are logged in as a user with these permissions.

This is the broken link - https://github.com/aws-samples/aws-workshop-for-kubernetes/blob/master/01-path-basics/101-start-here/aws-permissions.adoc

**Comment by geremyCohen** [comment]
@buzzsurfr the file doesn't appear to exist, and doesn't appear in the git history.  Can you give me a hint to what "these permissions" and/or aws-permissions.adoc is supposed to contain, and I can take it from there?

**Comment by geremyCohen** [comment]
Will create docs that list the permissions needed to run the workshop.

**Comment by geremyCohen** [comment]
Dupe of https://github.com/aws-samples/aws-workshop-for-kubernetes/issues/340

**Comment by geremyCohen** [comment]
https://github.com/aws-samples/aws-workshop-for-kubernetes/pull/516
