### ISSUE TITLE
Fix Numbering

### ISSUE THREAD

**Issue by mann1mal** [aws-samples/aws-workshop-for-kubernetes#465]
Track: OpenShift on AWS
Text: Wordpress Dockerfile

Issue Base URL: http://openshift.awsworkshop.io/index.html

Nitpicking here, but can we fix the enumeration on the steps in this section? It's just "1." repeated

**Comment by christopherhein** [comment]
@mandusm can we get the OS workshop updated to not submit to this one for issues?
