### ISSUE TITLE
Define a Contribution Policy

### ISSUE THREAD

**Issue by buzzsurfr** [aws-samples/aws-workshop-for-kubernetes#479]
Create a contribution policy to let contributors know how we will handle Issues/PRs.

**Comment by arun-gupta** [comment]
- Bugs to be closed after 15 days of inactivity
- Do not close your own PR, make sure its reviewed by at least another reviewer
- Who gets to be a maintainer?

**Comment by buzzsurfr** [comment]
I'm not sure how we should determine who is a maintainer, but I'm open to suggestions.
