### ISSUE TITLE
Add lab-ide-build.sh to this repo and persist AWS_STACK_NAME

### ISSUE THREAD

**Issue by markuskaiser** [aws-samples/aws-workshop-for-kubernetes#486]
Creating the worker nodes using

```
aws cloudformation create-stack \
  --stack-name k8s-workshop-worker-nodes \
  (...)
```

does not work (will CFN stack will rollback) as lab-ide-build.sh is not persisting AWS_STACK_NAME.
Would have issued a pull request but lab-ide-build.sh is not included in this repo.

https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/01-path-basics/102-your-first-cluster

**Comment by buzzsurfr** [comment]
lab-ide-build.sh is in [aws-workshop-for-kubernetes/01-path-basics/101-start-here/scripts/lab-ide-build.sh](https://github.com/aws-samples/aws-workshop-for-kubernetes/blob/master/01-path-basics/101-start-here/scripts/lab-ide-build.sh) for your review.

The intention was to use `AWS_MASTER_STACK` in the name for the creation of the worker nodes.
