### ISSUE TITLE
EKS create worker nodes issue

### ISSUE THREAD

**Issue by xiangshen-dk** [aws-samples/aws-workshop-for-kubernetes#502]
In the step '[create worker nodes](https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/01-path-basics/102-your-first-cluster#create-the-worker-nodes)', the variable AWS_MASTER_STACK is used for the key name. 

However in the script [lab-ide-build.sh](https://github.com/aws-samples/aws-workshop-for-kubernetes/blob/master/01-path-basics/101-start-here/scripts/lab-ide-build.sh), AWS_STACK_NAME is used to create the key. Since they don't have the same value, the 'create worker nodes' CF stack will fail.

**Comment by buzzsurfr** [comment]
Fixed in #503
