### ISSUE TITLE
The environment variables in the setup script need to persist.

### ISSUE THREAD

**Issue by nathanpeck** [aws-samples/aws-workshop-for-kubernetes#521]
In file this file there are environment variables exported ephemerally: https://github.com/aws-samples/aws-workshop-for-kubernetes/blob/master/01-path-basics/101-start-here/scripts/lab-ide-build.sh

However, subsequent steps ask you to close the terminal and restart it, causing all these environment variables to be lost, breaking the rest of the process. The environment variables should be set in a persistent way in the bash_profile so that they persist between terminal closes and reopens.

**Comment by dalbhanj** [comment]
This should be fixed. Please retry and re-open if the issue persists. Thanks
