### ISSUE TITLE
do not offer use the option to bring up Cloud9 in a region different from EKS

### ISSUE THREAD

**Issue by geremyCohen** [aws-samples/aws-workshop-for-kubernetes#526]
At https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/01-path-basics/101-start-here#user-content-build-script

It says: "If you deployed your Cloud9 IDE in any region not supported by EKS, you will need to manually set the AWS_DEFAULT_REGION environment variable to a region supported by EKS:"

This may lead to other issues not yet documented/tested, so for now, its best to just have the user create the Cloud9 in the same region as EKS.

**Comment by dalbhanj** [comment]
I think @buzzsurfr got this to work but I am not sure how. Are we creating Cloud9 in separate regions but creating VPC in regions supported by EKS?

**Comment by geremyCohen** [comment]
I think it reduces complexity by removing the option from the table for the workshop... if they want to do it for production or on their onw, then fine, but since the workshops need to be streamlined time-wise, I was thinking this just takes a potential stumbling point off the table.

**Comment by dalbhanj** [comment]
PR https://github.com/aws-samples/aws-workshop-for-kubernetes/pull/536 fixes this issue
