### ISSUE TITLE
Issue - Node CFN Creation Script fails because AWS_STACK_NAME is not an ENV Variable

### ISSUE THREAD

**Issue by judahb** [aws-samples/aws-workshop-for-kubernetes#527]
Solution - Include export AWS_STACK_NAME=<NAME OF STACK> and this should allow this command to work.

$ aws cloudformation create-stack \
  --stack-name k8s-workshop-worker-nodes \
  --template-url https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-06-05/amazon-eks-nodegroup.yaml \
  --capabilities "CAPABILITY_IAM" \
  --parameters "[{\"ParameterKey\": \"KeyName\", \"ParameterValue\": \"${AWS_STACK_NAME}\"},
                 {\"ParameterKey\": \"NodeImageId\", \"ParameterValue\": \"${EKS_WORKER_AMI}\"},
                 {\"ParameterKey\": \"ClusterName\", \"ParameterValue\": \"k8s-workshop\"},
                 {\"ParameterKey\": \"NodeGroupName\", \"ParameterValue\": \"k8s-workshop-nodegroup\"},
                 {\"ParameterKey\": \"ClusterControlPlaneSecurityGroup\", \"ParameterValue\": \"${EKS_SECURITY_GROUPS}\"},
                 {\"ParameterKey\": \"VpcId\", \"ParameterValue\": \"${EKS_VPC_ID}\"},
                 {\"ParameterKey\": \"Subnets\", \"ParameterValue\": \"${EKS_SUBNET_IDS}\"}]"

**Comment by JohnEspenhahn** [comment]
I am seeing this too, the ${AWS_STACK_NAME} can be replaced with:
${aws ec2 describe-key-pairs | grep -E [a-z0-9\\-]+k8s-workshop[a-z0-9\\-]+ -o}

**Comment by dalbhanj** [comment]
This should be fixed. Please retry and re-open if the issue persists. Thanks
