### ISSUE TITLE
An error occurred (UnsupportedAvailabilityZoneException) when calling the CreateCluster operation

### ISSUE THREAD

**Issue by dalbhanj** [aws-samples/aws-workshop-for-kubernetes#529]
Several users ran through the issue during EKS create cluster operation 
https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/01-path-basics/102-your-first-cluster#create-a-kubernetes-cluster-with-eks

Here is the error:
An error occurred (UnsupportedAvailabilityZoneException) when calling the CreateCluster operation: Cannot create cluster 'k8s-workshop' because us-east-1c, the targeted availability zone, does not currently have sufficient capacity to support the clust  er. Retry and choose from these availability zones: us-east-1a, us-east-1b, us-east-1d

**Comment by ltzenteno** [comment]
Hi, we encountered the exactly same issue, It appears that it is only a North Virginia issue (don't know why), we could create it in Oregon (us-west-2) without problems.
