### ISSUE TITLE
missing bearer tokens

### ISSUE THREAD

**Issue by sonicintrusion** [aws-samples/aws-workshop-for-kubernetes#541]
https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/02-path-working-with-clusters/201-cluster-monitoring

When listing the available tokens I get this:

```
$ kubectl get secret -n kube-system
NAME                               TYPE                                  DATA      AGE
aws-node-token-rzwsq               kubernetes.io/service-account-token   3         46m
default-token-rx789                kubernetes.io/service-account-token   3         46m
kube-dns-token-djv4x               kubernetes.io/service-account-token   3         46m
kube-proxy-token-xp9xg             kubernetes.io/service-account-token   3         46m
kubernetes-dashboard-certs         Opaque                                0         9m
kubernetes-dashboard-key-holder    Opaque                                2         9m
kubernetes-dashboard-token-frzj9   kubernetes.io/service-account-token   3         9m
```

The instructions say that I need to use the `namespace-controller-token` but it's not available.

One thing to note, I haven't missed any steps in workshop 2 but I built a fresh cluster after completing workshop 1. I couldn't see any steps in workshop 1 that would be reconfiguring the namespace controller so I can't tell why it's not there.

**Comment by subhrang** [comment]
+1. Facing the exact same issue

**Comment by carlosafonso** [comment]
It looks like EKS's default secrets do not include what the documentation says (this is just a guess). By following these steps [1], a secret called `eks-admin-token-xxxx` is created and I can login without problem.

[1] https://docs.aws.amazon.com/eks/latest/userguide/dashboard-tutorial.html#eks-admin-service-account

**Comment by sonicintrusion** [comment]
works great. nice and simple. 
thanks v. much
