### ISSUE TITLE
Helm chart repository

### ISSUE THREAD

**Issue by arun-gupta** [aws-samples/aws-workshop-for-kubernetes#70]
- Show how to setup a Helm chart repository
- Use S3 bucket for storing charts
- Host a `index.html` page that shows the list of charts
- Write a Lambda function to update the page whenever a new chart is uploaded

**Comment by marcellodesales** [comment]
@arun-gupta When will this chapter be available? Any resources?

**Comment by arun-gupta** [comment]
Nobody is working on it yet, so there is no ETA. Would you like to send a PR?

**Comment by marcellodesales** [comment]
@arun-gupta I'm still catching up on my conversion from `swarm` to `k8s` :) Thanks a lot! Your repos are awesome!

**Comment by christopherhein** [comment]
@arun-gupta mind if I do this using `chartmuseum` instead? https://github.com/kubernetes-helm/chartmuseum

**Comment by arun-gupta** [comment]
LGTM

Wondering what does @michelleN think about it?

**Comment by christopherhein** [comment]
One issue I potentially see with my implementation - https://github.com/kubernetes-helm/chartmuseum/issues/66

My module walks through deploying, then setting up an s3 bucket to augment the storage, then exposes it using an ELB, then we add authentication. I have a note saying that this will expose your repo to the world which might not be best for all repositories.

**Comment by marcellodesales** [comment]
@christopherhein I will definitely try that!
